'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {createPortal} from 'react-dom';
import {Sun,Moon,Settings2,ImagePlus,Copy,Download,ArrowLeft,ArrowRight,ArrowUp,ArrowDown,Heart,Shuffle,Monitor,Trash2,X,Lock,LockOpen} from 'lucide-react';
import {PalettMark} from './mark';

import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle} from '@/components/ui/alert-dialog';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {Palette,seeds,theme,css,markdown,ink,validPalette,parseHex,withLockedBackground} from '@/lib/palettes';
import {Settings} from './settings';
import {Importer} from './importer';
import {PaletteCard} from './card';
import {imageFile,fromClipboardData,capturePalette} from '@/lib/capture';
import '@/lib/desktop';
function download(name:string,content:string,type='text/plain'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function PaletteApp(){
 const [palettes,setPalettes]=useState<Palette[]>(seeds),[selected,setSelected]=useState('seed-12'),[filter,setFilter]=useState('all'),[view,setView]=useState('grid'),[appearance,setAppearance]=useState('system'),[systemDark,setSystemDark]=useState(false),[settings,setSettings]=useState(false),[settingsTab,setSettingsTab]=useState('app'),[importing,setImporting]=useState(false),[file,setFile]=useState<File|null>(null),[exporting,setExporting]=useState<Palette|null>(null),[dragging,setDragging]=useState(false),[dragPreview,setDragPreview]=useState(''),[loadError,setLoadError]=useState(''),[loading,setLoading]=useState(true),[clipboardFallback,setClipboardFallback]=useState(''),[zoom,setZoom]=useState(1),[autoImportOnDrop,setAutoImportOnDrop]=useState(false),[hideKeyboardGuide,setHideKeyboardGuide]=useState(false),[bgLock,setBgLock]=useState<string|null>(null),[menu,setMenu]=useState<{p:Palette;x:number;y:number}|null>(null),[pendingDelete,setPendingDelete]=useState<Palette|null>(null),[desktop,setDesktop]=useState(false);
 const restoreInput=useRef<HTMLInputElement>(null),dragDepth=useRef(0),dragPreviewUrl=useRef(''),silentBusy=useRef(false),queue=useRef(Promise.resolve()),state=useRef({palettes,selected});state.current={palettes,selected};
 function clearDragPreview(){if(dragPreviewUrl.current){URL.revokeObjectURL(dragPreviewUrl.current);dragPreviewUrl.current='';}setDragPreview('');}
 function peekDrag(dt:DataTransfer){const f=imageFile(dt);if(!f||dragPreviewUrl.current)return;dragPreviewUrl.current=URL.createObjectURL(f);setDragPreview(dragPreviewUrl.current);}
 const active=palettes.find(p=>p.id===selected)||palettes[0];const dark=appearance==='system'?systemDark:appearance==='dark';const visible=filter==='favorites'?palettes.filter(p=>p.favorite):palettes;
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/palettes');if(!r.ok)throw new Error('Your saved collection could not be loaded.');const list=await r.json();if(!Array.isArray(list)||!list.every(validPalette))throw new Error('Collection response is invalid.');const order=new Map(seeds.map((p,i)=>[p.id,i]));list.sort((a,b)=>(order.get(a.id)??1000)-(order.get(b.id)??1000));setPalettes(list);setLoadError('');}catch(e){setLoadError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>window.paletteDesktop?.onCollectionChanged(()=>{void queue.current.then(()=>load());}),[load]);
 useEffect(()=>{if(window.paletteDesktop){document.documentElement.classList.add('is-desktop');setDesktop(true);}},[]);
 useEffect(()=>window.paletteDesktop?.onOpenSettings(()=>{setSettingsTab('menubar');setSettings(true);}),[]);
 useEffect(()=>{function paste(e:ClipboardEvent){if(settings||importing||exporting||clipboardFallback)return;const f=imageFile(e.clipboardData);if(f){e.preventDefault();setFile(f);setImporting(true);}else if(window.paletteDesktop){void window.paletteDesktop.readClipboardImage().then(data=>{if(data){setFile(fromClipboardData(data));setImporting(true);}}).catch(()=>toast.error('Could not read clipboard image.'));}}window.addEventListener('paste',paste);return()=>window.removeEventListener('paste',paste);},[settings,importing,exporting,clipboardFallback]);
 useEffect(()=>{load();const mq=matchMedia('(prefers-color-scheme: dark)');setSystemDark(mq.matches);const fn=()=>setSystemDark(mq.matches);mq.addEventListener('change',fn);try{const prefs=JSON.parse(localStorage.getItem('palette-prefs')||'{}');if(['light','dark','system'].includes(prefs.appearance))setAppearance(prefs.appearance);if(['list','grid'].includes(prefs.view))setView(prefs.view);if(prefs.selected)setSelected(prefs.selected);if(typeof prefs.zoom==='number'&&prefs.zoom>=0.75&&prefs.zoom<=1.4)setZoom(prefs.zoom);if(prefs.autoImportOnDrop)setAutoImportOnDrop(true);if(prefs.hideKeyboardGuide)setHideKeyboardGuide(true);if(typeof prefs.bgLock==='string'){const hex=parseHex(prefs.bgLock);if(hex)setBgLock(hex);}}catch{}return()=>mq.removeEventListener('change',fn);},[load]);
 useEffect(()=>{if(loading)return;try{localStorage.setItem('palette-prefs',JSON.stringify({appearance,view,selected,zoom,autoImportOnDrop,hideKeyboardGuide,bgLock}));}catch{}},[appearance,view,selected,zoom,autoImportOnDrop,hideKeyboardGuide,bgLock,loading]);
 useEffect(()=>{document.documentElement.style.zoom='';const shell=document.querySelector('.app-shell') as HTMLElement|null;if(shell)shell.style.zoom=String(zoom);},[zoom]);
 useEffect(()=>{if(!menu)return;function close(){setMenu(null);}function onKey(e:KeyboardEvent){if(e.key==='Escape')close();}window.addEventListener('mousedown',close);window.addEventListener('scroll',close,true);window.addEventListener('keydown',onKey);return()=>{window.removeEventListener('mousedown',close);window.removeEventListener('scroll',close,true);window.removeEventListener('keydown',onKey);};},[menu]);
 useEffect(()=>{const t=withLockedBackground(theme(active,dark),bgLock,dark);const root=document.documentElement;Object.entries(t).forEach(([k,v])=>root.style.setProperty('--'+k,v));const mapped={foreground:t.text,card:t.surface,'card-foreground':t.text,popover:t.surface,'popover-foreground':t.text,primary:t.accent,'primary-foreground':t['on-accent'],secondary:t.raised,'secondary-foreground':t.text,muted:t.raised,'muted-foreground':t.muted,'accent-foreground':t['on-accent'],input:t.border,ring:t.focus,destructive:t.danger};Object.entries(mapped).forEach(([k,v])=>root.style.setProperty('--'+k,v));root.dataset.theme=dark?'dark':'light';root.style.colorScheme=dark?'dark':'light';},[active,dark,bgLock]);
 const save=useCallback(async(p:Palette)=>{if(!validPalette(p))return false;try{const r=await fetch('/api/palettes',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});if(!r.ok)throw new Error();return true;}catch{return false;}},[]);
 const change=useCallback((p:Palette)=>{setPalettes(prev=>prev.map(x=>x.id===p.id?p:x));queue.current=queue.current.then(async()=>{if(!await save(p))toast.error('Changes not saved',{description:'Your change is still visible.',action:{label:'Retry',onClick:()=>{const latest=state.current.palettes.find(x=>x.id===p.id)||p;void save(latest).then(ok=>ok?toast.success('Saved'):toast.error('Still unable to save.'));}}});});},[save]);
 const pick=useCallback((id:string)=>setSelected(id),[]);
 const rotate=useCallback((n:number)=>{const p=state.current.palettes.find(p=>p.id===state.current.selected)||state.current.palettes[0];change({...p,main:(p.main+n+p.colors.length)%p.colors.length});},[change]);
 const shuffle=useCallback(()=>{const list=(filter==='favorites'?state.current.palettes.filter(p=>p.favorite):state.current.palettes).filter(p=>p.id!==state.current.selected);if(list.length)pick(list[Math.floor(Math.random()*list.length)].id);else toast('Add another palette to shuffle.');},[filter,pick]);
 const toggleLock=useCallback(()=>{setBgLock(prev=>{if(prev)return null;const hex=parseHex(getComputedStyle(document.documentElement).getPropertyValue('--background'))||parseHex(theme(state.current.palettes.find(p=>p.id===state.current.selected)||state.current.palettes[0],dark).background);return hex;});},[dark]);
 const copy=useCallback(async(p:Palette)=>{const text=css(p);try{if(window.paletteDesktop)await window.paletteDesktop.copyCSS(text);else await navigator.clipboard.writeText(text);toast.success('CSS copied',{description:'Light + soft dark, with the selected main color.'});}catch{setClipboardFallback(text);}},[]);
 const copyHex=useCallback(async(color:string)=>{try{if(window.paletteDesktop)await window.paletteDesktop.copyCSS(color);else await navigator.clipboard.writeText(color);toast.success(color+' copied');}catch{toast.error('Could not copy '+color);}},[]);
 useEffect(()=>{function key(e:KeyboardEvent){const inField=e.target instanceof HTMLElement&&!!e.target.closest('input,textarea,select,[contenteditable="true"],[role="dialog"],[role="menu"],[role="listbox"]');const cmd=e.metaKey||e.ctrlKey;if(cmd&&(e.key==='c'||e.key==='C')&&!e.altKey&&!e.shiftKey){if(inField||settings||importing||exporting||clipboardFallback||window.getSelection()?.toString())return;e.preventDefault();void copy(active);return;}if(cmd&&(e.code==='Equal'||e.key==='+'||e.key==='=')){e.preventDefault();setZoom(z=>Math.min(1.4,Math.round((z+0.1)*10)/10));return;}if(cmd&&(e.code==='Minus'||e.key==='-')){e.preventDefault();setZoom(z=>Math.max(0.75,Math.round((z-0.1)*10)/10));return;}if(cmd&&e.code==='Digit0'){e.preventDefault();setZoom(1);return;}if(settings||importing||exporting||clipboardFallback||cmd||e.altKey||inField)return;if(e.code==='Space'){e.preventDefault();shuffle();}if(e.key==='l'||e.key==='L'){e.preventDefault();toggleLock();return;}if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();rotate(e.key==='ArrowLeft'?-1:1);}if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();const i=visible.findIndex(p=>p.id===selected);const p=visible[(i+(e.key==='ArrowDown'?1:-1)+visible.length)%visible.length];if(p){pick(p.id);document.querySelector(`[data-palette="${p.id}"]`)?.scrollIntoView({block:'nearest',behavior:'instant'});}}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[settings,importing,exporting,clipboardFallback,shuffle,rotate,visible,selected,pick,copy,active,toggleLock]);
 useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const life=new AbortController();for(const tool of [{name:'list_palettes',description:'Read the current palette collection, including favorite and main color.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({palettes:state.current.palettes})},{name:'select_palette',description:'Select a palette and recolor the entire app. Does not change its colors.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},execute:async(input:any)=>{if(typeof input?.id!=='string'||!state.current.palettes.some(p=>p.id===input.id))throw new Error('Unknown palette');pick(input.id);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {selected:input.id};}}]){try{Promise.resolve(mc.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}}return()=>life.abort();},[pick]);
 const add=async(p:Palette)=>{if(!await save(p))return false;setPalettes(prev=>[...prev.filter(x=>x.id!==p.id),p]);setSelected(p.id);setFilter('all');toast.success('Palette added');if(window.paletteDesktop){try{const prefs=await window.paletteDesktop.getPreferences();if(prefs.autoCopyCSS){await window.paletteDesktop.copyCSS(css(p));toast.success('Light + dark CSS copied');}}catch{toast.error('Palette saved, but CSS could not be copied.');}}return true;};
 function openMenu(e:React.MouseEvent,p:Palette){const w=230,h=188;setMenu({p,x:Math.max(8,Math.min(e.clientX,window.innerWidth-w-8)),y:Math.max(8,Math.min(e.clientY,window.innerHeight-h-8))});}
 async function removePalette(p:Palette){if(palettes.length<=1){toast.error('Keep at least one palette.');return;}const leftover=palettes.filter(x=>x.id!==p.id);setPalettes(leftover);if(selected===p.id)setSelected(leftover[0].id);try{const r=await fetch('/api/palettes?id='+encodeURIComponent(p.id),{method:'DELETE'});if(!r.ok)throw new Error();toast.success('Palette deleted');}catch{toast.error('Could not delete. It is hidden here until reload.',{action:{label:'Retry',onClick:()=>{void removePalette(p);}}});}}
 async function silentImport(f:File){if(silentBusy.current){toast.error('A palette is already saving. Try this image again in a moment.');return;}silentBusy.current=true;const id=toast.loading('Extracting palette…');try{const p=await capturePalette(f);toast.dismiss(id);if(!await add(p))toast.error('Could not save the palette.');}catch(e){toast.dismiss(id);toast.error((e as Error).message);}finally{silentBusy.current=false;}}
 async function restore(f:File){try{if(f.size>2000000)throw new Error('Collection file is too large.');const j=JSON.parse(await f.text());if(!Array.isArray(j.palettes)||j.palettes.length>1000||!j.palettes.every(validPalette))throw new Error('Choose a valid Palette collection JSON file.');let count=0;for(const p of j.palettes){if(!await save(p))throw new Error(`${count} palettes imported before saving failed. Retry importing to finish.`);count++;}await load();toast.success(`${count} palettes imported`);}catch(e){toast.error((e as Error).message);}}
 return <div className={'app-shell'+(hideKeyboardGuide?' no-keys':'')} onDragEnter={e=>{e.preventDefault();if(!importing&&e.dataTransfer.types.includes('Files')){dragDepth.current++;setDragging(true);peekDrag(e.dataTransfer);}}} onDragLeave={e=>{e.preventDefault();dragDepth.current--;if(dragDepth.current<=0){setDragging(false);clearDragPreview();}}} onDragOver={e=>{e.preventDefault();if(!importing)peekDrag(e.dataTransfer);}} onDrop={e=>{e.preventDefault();dragDepth.current=0;setDragging(false);clearDragPreview();if(importing)return;const dropped=imageFile(e.dataTransfer)||e.dataTransfer.files[0];if(!dropped)return;if(autoImportOnDrop){void silentImport(dropped);return;}setFile(dropped);setImporting(true);}}>
 <header className="topbar"><a className="brand" href="/" aria-label="Pallet home"><PalettMark/><span className="brand-lockup"><span className="brand-name">PALLET</span><span className="brand-by">/ by KIKA</span></span></a><div className="top-actions"><button className="icon-button fav-toggle" title={filter==='favorites'?'Show all':'Show favorites'} aria-label={filter==='favorites'?'Show all palettes':'Show favorites'} aria-pressed={filter==='favorites'} onClick={()=>setFilter(filter==='favorites'?'all':'favorites')}><Heart fill={filter==='favorites'?'currentColor':'none'} strokeWidth={1.65}/></button><button className="icon-button bg-lock" title={bgLock?`Unlock background ${bgLock}`:'Lock background'} aria-label={bgLock?'Unlock background':'Lock background'} aria-pressed={!!bgLock} onClick={toggleLock}>{bgLock?<Lock strokeWidth={1.65}/>:<LockOpen strokeWidth={1.65}/>}</button><button className="icon-button" title="Copy CSS" aria-label="Copy CSS" onClick={()=>copy(active)}><Copy/></button><button className="icon-button" title="Export selected theme" aria-label="Export selected theme" onClick={()=>setExporting(active)}><Download/></button><button className="icon-button" title={`Switch to ${dark?'light':'soft dark'} mode`} aria-label={`Switch to ${dark?'light':'dark'} mode`} onClick={()=>setAppearance(dark?'light':'dark')}>{dark?<Moon/>:<Sun/>}</button><button className="icon-button" aria-label="Settings" onClick={()=>{setSettingsTab('app');setSettings(true);}}><Settings2/></button><button className="icon-button" title="Add image" aria-label="Add image" onClick={()=>{setFile(null);setImporting(true);}}><ImagePlus/></button>{desktop&&<button className="icon-button window-close" title="Close" aria-label="Close" onClick={()=>void window.paletteDesktop?.hideMain()}><X/></button>}</div></header>
 <main>
 <section className="active-palette" aria-label="Selected palette">
 <div className="main-swatches">{active.colors.map((color,i)=><div key={i} className={'main-swatch'+(i===active.main?' is-main':'')} style={{background:color,color:ink(color)}}><button type="button" className="main-swatch-hit" aria-label={`Make ${color} primary`} aria-pressed={i===active.main} onClick={()=>change({...active,main:i})}/><button type="button" className="hex-chip" aria-label={`Copy ${color}`} title={`Copy ${color}`} onClick={()=>void copyHex(color)}>{i===active.main&&<i/>}{color}</button></div>)}</div>
 <div className="rotation"><button className="icon-button filled" title="Previous main color" aria-label="Previous main color" onClick={()=>rotate(-1)}><ArrowLeft/></button><p className="palette-caption"><strong>{active.name}</strong><span>{active.colors.length} colors</span><span>{dark?'Soft dark':'Light'}</span></p><button className="icon-button filled" title="Next main color" aria-label="Next main color" onClick={()=>rotate(1)}><ArrowRight/></button></div>
 {active.source.includes('estimated')&&<p className="helper source-note">{active.source}</p>}
 </section>
 <section className="collection-section" aria-label="Palette collection">
 {loadError&&<div className="notice warning" role="alert">{loadError} Showing starter palettes. <button onClick={load}>Retry</button></div>}
 <div className={'collection '+view} aria-busy={loading}>{visible.map(p=><PaletteCard key={p.id} p={p} active={p.id===selected} select={()=>pick(p.id)} favorite={()=>change({...p,favorite:!p.favorite})} copy={()=>copy(p)} onMenu={openMenu}/>)}</div>
 {!visible.length&&<div className="empty-state"><Heart/><h3>No favorites yet</h3><p>Tap a heart or right-click any palette to keep it here.</p><button className="button" onClick={()=>setFilter('all')}>View collection</button></div>}
 <div className="collection-tools"><span>Drop or paste an image anywhere. Long-press a card to copy CSS.</span><button onClick={()=>download('palette-collection.json',JSON.stringify({version:1,palettes:palettes.map(p=>({...p,light:theme(p,false),dark:theme(p,true)}))},null,2),'application/json')}>Export collection</button><button onClick={()=>restoreInput.current?.click()}>Import collection</button><input ref={restoreInput} hidden type="file" accept="application/json" onChange={e=>{if(e.target.files?.[0])restore(e.target.files[0]);e.target.value='';}}/></div>
 </section></main>
 {!hideKeyboardGuide?<footer className="keyboard-bar"><button onClick={shuffle}><kbd>Space</kbd> Shuffle</button><span><kbd>⌘C</kbd> Copy CSS</span><span><kbd>L</kbd> Lock</span><span><kbd>⌘−</kbd><kbd>⌘+</kbd> Size</span><span><kbd><ArrowUp/><ArrowDown/></kbd> Navigate</span><span><kbd><ArrowLeft/><ArrowRight/></kbd> Rotate color</span><span className="footer-count" aria-label={`${palettes.length} palettes`}>{palettes.length}</span><span className="footer-mode">{appearance==='system'&&<Monitor/>}{dark?'Soft dark':'Light'}</span></footer>:<div className="footer-count solo" aria-label={`${palettes.length} palettes`}>{palettes.length}</div>}
 <button className="mobile-shuffle" onClick={shuffle} aria-label="Shuffle palettes"><Shuffle/>Shuffle</button>
 {dragging&&<div className="drag-overlay">{dragPreview?<img src={dragPreview} alt=""/>:<ImagePlus/>}<h2>Drop to extract a palette</h2></div>}
 <Settings open={settings} onClose={()=>setSettings(false)} tab={settingsTab} setTab={setSettingsTab} appearance={appearance} setAppearance={setAppearance} autoImportOnDrop={autoImportOnDrop} setAutoImportOnDrop={setAutoImportOnDrop} hideKeyboardGuide={hideKeyboardGuide} setHideKeyboardGuide={setHideKeyboardGuide} view={view} setView={setView} bgLock={bgLock} setBgLock={setBgLock}/>
 <Importer open={importing} onClose={()=>setImporting(false)} file={file} onSave={add}/>
 <Dialog open={!!exporting} onOpenChange={v=>!v&&setExporting(null)}><DialogContent><DialogTitle>Export {exporting?.name}</DialogTitle><DialogDescription>Every theme export includes light and soft-dark modes.</DialogDescription><div className="export-options">{exporting&&[['CSS variables','.css',css(exporting),'text/css'],['Markdown theme','.md',markdown(exporting),'text/markdown'],['Palette JSON','.json',JSON.stringify({...exporting,light:theme(exporting,false),dark:theme(exporting,true)},null,2),'application/json']].map(([label,ext,content,mime])=><button className="button" key={ext} onClick={()=>download(exporting.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')+ext,content,mime)}><Download/>{label}</button>)}</div></DialogContent></Dialog>
 <Dialog open={!!clipboardFallback} onOpenChange={v=>!v&&setClipboardFallback('')}><DialogContent><DialogTitle>Copy CSS</DialogTitle><DialogDescription>Your browser blocked automatic copying. Select and copy the CSS below.</DialogDescription><textarea aria-label="Theme CSS" className="css-output" value={clipboardFallback} readOnly onFocus={e=>e.target.select()}/></DialogContent></Dialog>
 {menu&&createPortal(<div className="palette-ctx" role="menu" style={{left:menu.x,top:menu.y}} onMouseDown={e=>e.stopPropagation()}><button type="button" role="menuitem" onClick={()=>{copy(menu.p);setMenu(null);}}><Copy/>Copy CSS (light + dark)</button><button type="button" role="menuitem" onClick={()=>{setExporting(menu.p);setMenu(null);}}><Download/>Export theme</button><button type="button" role="menuitem" className={'is-heart'+(menu.p.favorite?' is-fav':'')} aria-label={menu.p.favorite?'Remove favorite':'Favorite'} aria-pressed={menu.p.favorite} onClick={()=>{const next={...menu.p,favorite:!menu.p.favorite};change(next);setMenu({...menu,p:next});}}><Heart fill={menu.p.favorite?'currentColor':'none'}/></button><button type="button" role="menuitem" className="is-danger" onClick={()=>{setPendingDelete(menu.p);setMenu(null);}}><Trash2/>Delete</button></div>,document.body)}
 <AlertDialog open={!!pendingDelete} onOpenChange={v=>!v&&setPendingDelete(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete {pendingDelete?.name}?</AlertDialogTitle><AlertDialogDescription>This removes it from your collection. You can add it again from an image later.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={()=>{if(pendingDelete)void removePalette(pendingDelete);setPendingDelete(null);}}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Toaster/>
 </div>;
}
