'use client';
import {useEffect,useState,forwardRef,useImperativeHandle,useRef} from 'react';
import type {CapturePreferences,CaptureSize} from '@/lib/desktop';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {displayShortcut,eventToAccelerator} from '@/lib/shortcut';
const fallback:CapturePreferences={autoCopyCSS:false,shortcut:'CommandOrControl+Shift+P',shortcutRegistered:true,captureSize:'mo'};
const sizes:{id:CaptureSize;label:string;hint:string}[]=[{id:'mini',label:'Mini',hint:'Smallest'},{id:'miny',label:'Miny',hint:'Medium'},{id:'mo',label:'Mo',hint:'Current size'}];
export type CaptureSettingsHandle={save:()=>Promise<boolean>};
export const CaptureSettings=forwardRef<CaptureSettingsHandle,{}>(function CaptureSettings(_,ref){
 const [prefs,setPrefs]=useState<CapturePreferences|null>(null),[error,setError]=useState(''),[recording,setRecording]=useState(false);
 const loaded=useRef<CapturePreferences|null>(null);
 useEffect(()=>{let live=true;(async()=>{try{const next=window.paletteDesktop?await window.paletteDesktop.getPreferences():(()=>{try{const p=JSON.parse(localStorage.getItem('palette-capture')||'{}');return {autoCopyCSS:!!p.autoCopyCSS,shortcut:typeof p.shortcut==='string'?p.shortcut:fallback.shortcut,shortcutRegistered:true,captureSize:p.captureSize==='mini'||p.captureSize==='miny'||p.captureSize==='mo'?p.captureSize:'mo'};}catch{return fallback;}})();if(!live)return;if(!next.captureSize)next.captureSize='mo';loaded.current=next;setPrefs(next);}catch{if(live)setError('Could not load capture settings.');}})();return()=>{live=false;};},[]);
 useEffect(()=>{if(!recording)return;function onKey(e:KeyboardEvent){if(e.key==='Escape'){setRecording(false);return;}e.preventDefault();e.stopPropagation();const next=eventToAccelerator(e);if(!next)return;setPrefs(p=>p?{...p,shortcut:next}:p);setRecording(false);}window.addEventListener('keydown',onKey,true);return()=>window.removeEventListener('keydown',onKey,true);},[recording]);
 useImperativeHandle(ref,()=>({save:async()=>{if(!prefs)return false;try{if(window.paletteDesktop){const next=await window.paletteDesktop.setPreferences(prefs);setPrefs(next);loaded.current=next;}else{localStorage.setItem('palette-capture',JSON.stringify({autoCopyCSS:prefs.autoCopyCSS,shortcut:prefs.shortcut,captureSize:prefs.captureSize}));const next={...prefs,shortcutRegistered:true};setPrefs(next);loaded.current=next;}return true;}catch(e){setError((e as Error).message);return false;}}}),[prefs]);
 if(!prefs)return null;
 return <section className="capture-settings"><div className="field"><label>Drop zone size</label><RadioGroup className="appearance size-picks" value={prefs.captureSize} onValueChange={v=>setPrefs({...prefs,captureSize:v as CaptureSize})}>{sizes.map(s=><label key={s.id}><RadioGroupItem value={s.id}/><span>{s.label}<em>{s.hint}</em></span></label>)}</RadioGroup></div><label className="capture-checkbox"><input type="checkbox" checked={prefs.autoCopyCSS} onChange={e=>setPrefs({...prefs,autoCopyCSS:e.target.checked})}/>Copy CSS when closing the drop zone with Esc</label><p className="helper">Esc always closes and resets the drop zone. When this is on, Esc also copies light + dark CSS. Add image in the collection still copies after save if this is on.</p><div className="field"><span id="capture-shortcut-label">Global shortcut</span><button type="button" className={'shortcut-record'+(recording?' is-recording':'')} aria-labelledby="capture-shortcut-label" onClick={()=>setRecording(true)}>{recording?'Press the new shortcut…':displayShortcut(prefs.shortcut)||'Click to record'}</button><p>Click, then press the keys. Esc cancels. Opens the drop zone from any app; ⌘V pastes while it is open.</p></div>{!prefs.shortcutRegistered&&<p className="warning">Shortcut unavailable. Try another key combination.</p>}{error&&<p role="alert" className="warning">{error}</p>}</section>;
});
